/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useStore } from '@/Store'
export function Tshirt(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/TShirt.glb')
  const material = useStore((state) => state.material)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Tshirt.geometry} material={material || materials.Shirt} position={[0.42, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/TShirt.glb')
